$(function() {
    var availableTowns = [
        "Girona",
        "Figueres",
        "Lloret de mar",
        "Blanes",
        "Olot",
        "Salt",
        "Palafrugell",
        "Sant Feliu de Guíxols",
        "Roses",
        "Banyoles",
        "Palamós",
        "Santa Coloma de Farners",
        "Castelló d'Empúries",
        "Torroella de Montgrí",
        "Ripoll",
        "Calonge",
        "L'Escala",
        "La Bisbal d'Empordà",
        "Castell-Platja d'Aro",
        "Cassà de la Selva",
        "Puigcerdà",
        "Llagostera",
        "Vidreres",
        "Maçanet de la Selva",
        "Caldes de Malavella",
        "Arbúcies",
        "Tossa de Mar",
        "Sant Hilari Sacalm",
        "Anglès",
        "Sils",
        "Vilafant",
        "Llança",
        "Santa Cristina d'Aro",
        "Celrà",
        "Sarrià de Ter",
        "Bescanó",
        "Porqueres",
        "Begur",
        "Hostalric",
        "Riells i Viabrea",
        "Breda",
        "Sant Joan de les Abadesses",
        "Campdevànol ",
        "Sant Julià de Ramis", 	
        "Sant Gregori", 	
        "Quart", 	
        "La Jonquera", 	
        "Vilobí d'Onyar", 	
        "Cadaqués",
        "La Vall d'en Bas",
        "Sant Joan les Fonts",
        "Pals",
        "Camprodon",
        "Vilablareix",
        "Fornells de la Selva",
        "Besalú",
        "Amer",
        "Cornellà del Terri",
        "Riudarenes",
        "Sant Pere Pescador",
        "La Cellera de Ter",
        "Riudellots de la Selva",
        "Ribes de Freser",
        "Peralada",
        "Mont-ras",
        "Forallac",
        "Les Preses",
        "Alp",
        "Bordils",
        "Les Planes d'Hostoles",
        "Llívia",
        "Santa Pau",
        "Avinyonet de Puigventós",
        "Palau-saverdera",
        "Fontcoberta",
        "Sant Feliu de Pallerols",
        "Corçà",
        "La Vall de Bianya",
        "Portbou",
        "Cruïlles, Monells i Sant Sadurní de l'Heura",
        "Sant Julià del Llor i Bonmatí",
        "Navata",
        "Verges",
        "Llers",
        "Vilajuïga",
        "Serinyà",
        "Vilamalla",
        "Viladrau",
        "Ullà",
        "Flaçà",
        "El Port de la Selva",
        "Castellfollit de la Roca",
        "Montagut i Oix",
        "Cabanes",
        "Vilabertran",
        "Cervià de Ter",
        "Vall-llobrega",
        "L'Armentera",
        "Garriguella",
        "Agullana",
        "Ventalló",
        "Saus, Camallera i Llampaies",
        "Vilademuls",
        "Sant Jaume de Llierca",
        "Sant Feliu de Buixalleu",
        "Sant Miquel de Fluvià",
        "Tortellà",
        "Aiguaviva",
        "Maçanet de Cabrenys",
        "Llambilles",
        "Lladó",
        "Albons",
        "Borrassà",
        "Massanes",
        "Torroella de Fluvià",
        "Sant Pau de Segúries",
        "Camós",
        "Sant Jordi Desvalls",
        "Bellcaire d'Empordà",
        "Fortià",
        "Vila-sacra",
        "Capmany",
        "Canet d'Adri",
        "Colera",
        "Sant Martí de Llémena",
        "Pau",
        "Guils de Cerdanya",
        "Llanars",
        "El Far d'Empordà",
        "Sant Climent Sescebes",
        "Darnius",
        "Sant Joan de Mollet",
        "Pont de Molins",
        "Campllong",
        "Vilallonga de Ter",
        "Palol de Revardit",
        "Ger",
        "Fontanals de Cerdanya",
        "Viladamat",
        "Osor",
        "Esponellà",
        "La Tallada d'Empordà",
        "Riudaura",
        "La Pera",
        "Maià de Montcal",
        "Argelaguer",
        "Espolla",
        "Jafre",
        "Bolvir",
        "Brunyola",
        "Garrigàs",
        "Parlavà",
        "Ordis",
        "Vilanant",
        "Gualta",
        "Molló",
        "Sant Aniol de Finestres",
        "Santa Llogaia d'Àlguema",
        "Juià",
        "Mieres",
        "Cantallops",
        "Isòvol",
        "Foixà",
        "Terrades",
        "Planoles",
        "Regencós",
        "Vilamacolum",
        "Masarac",
        "Palau-sator",
        "Cistella",
        "Ullastret",
        "Crespià",
        "Madremanya",
        "Sant Martí Vell",
        "Boadella i les Escaules",
        "Ogassa",
        "Biure",
        "Cabanelles",
        "Riumors",
        "Rupià",
        "Sant Miquel de Campmajor",
        "Pontós",
        "Sant Ferriol",
        "Sant Llorenç de la Muga",
        "Vallfogona de Ripollès",
        "Les Llosses",
        "Das",
        "Vilopriu",
        "Ultramort",
        "Viladasens",
        "Gombrèn",
        "La Selva de Mar",
        "Serra de Daró",
        "Urús",
        "Espinelves",
        "Colomers",
        "Rabós",
        "Sant Mori",
        "Torrent",
        "Queralbs",
        "Siurana",
        "Mollet de Peralada",
        "Setcases",
        "Pedret i Marzà",
        "Vilamaniscle",
        "Beuda",
        "Fontanilles",
        "Vidrà",
        "Garrigoles",
        "Toses",
        "Pardines",
        "Sant Andreu Salou",
        "Albanyà",
        "Vilaür",
        "Sales de Llierca",
        "Campelles",
        "Susqueda",
        "Palau de Santa Eulàlia",
        "La Vajol",
        "Meranges"
    ];
    $( "#poble" ).autocomplete({
        source: availableTowns
    });
});